### ISSUE TITLE
ZFS 2.1.7 Released

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [openzfsonwindows/openzfs#189]
With the recent ZFS 2.1.7 coming out - can this too be updated to match?

**Comment by sskras** [comment]
I guess you have missed some existing issues and instead created a new one. No?
Otherwise it's hard for me to get any other ideas here. No offense:)

**Comment by sskras** [comment]
Since the project [started delivering](https://github.com/openzfsonwindows/openzfs/tags) v2.2.0 this summer:
![image](https://github.com/openzfsonwindows/openzfs/assets/7887758/2d46affb-2147-4b9e-8fbc-4915059c607d)

Updating to v2.1.7 seems to be finished in 2023 Apr 15:
![image](https://github.com/openzfsonwindows/openzfs/assets/7887758/04cf9c82-061d-46b2-b504-d160214155bf)

So I believe the issue is fixed already and should be closed.

**Comment by Chewbakka-Wakka** [comment]
That's right!
