### ISSUE TITLE
Is `OpenZFSOnWindows-debug-2.1.7rc2-dirty.exe` suitable?

### ISSUE THREAD

**Issue by bilogic** [openzfsonwindows/openzfs#219]
Hi,

I tried to open a discussion but it lead to openzfs's repo. So decided to ask here instead.. I'm planning to setup proxmox to run on ZFS and would like the Windows guest to be able to access the host ZFS/shared folders with Linux etc.

It is a personal machine, so is `OpenZFSOnWindows-debug-2.1.7rc2-dirty.exe` suitable? What kind of issues will I potentially face in my Windows host?

**Comment by lundman** [comment]
It is the most recent build of OpenZFS for Windows, yes, so you will have the best chance of getting something to work. But that is not something I have tried, so you are likely to discover bugs. If you do, file them here.

For shared folders, typically you would do that with NFS or similar, since only one OS would be able to mount the pool at any one time if it was ZFS storage.

**Comment by bilogic** [comment]
Oh, thank you, isn't file system and sharing via SMB separate matters?

My plan was to have proxmox mount the ZFS and share them via SMB for the Windows/Linux hosts.

**Comment by andrewc12** [comment]
Then windows/linux would only need smb not zfs

**Comment by bilogic** [comment]
@andrewc12 thanks, you cleared it right up for me. Thank you!
