### ISSUE TITLE
zfs destroy is failing

### ISSUE THREAD

**Issue by datacore-rm** [openzfsonwindows/openzfs#47]
zfs destroy is failing most of the times. It is failing at dsl_destroy_head_check_impl() where it expects holds to be 0, but is 1 as in  https://github.com/openzfsonwindows/openzfs/issues/9

![image](https://user-images.githubusercontent.com/84957265/135652901-c488abb7-6e73-4c25-9838-a823cb21bd56.png)

**Comment by datacore-rm** [comment]
This issue is same as you have documented in zfs_windows_unmount(). The 'ds_longholds' ref count is held during zfs mount and released during zfs unmount. So in successful case, zfs.exe is able to find mount point and sends unmount ioctl and followed by destroy ioctl. In failure case, zfs.exe is not able to find mount point and it only sends destroy command and hence ref count is not decreased.

But compared to zfsin, function zfs_remove_driveletter()  is still called from zfs_windows_unmount(). If this function call is commented, then this functionality works fine as in zfsin


		// Delete mountpoints for our volume manually
		// Query the mountmgr for mountpoints and delete them
		// until no mountpoint is left Because we are not satisfied
		// with mountmgrs work, it gets offended and doesn't
		// automatically create mointpoints for our volume after we
		// deleted them manually But as long as we recheck that in
		// mount and create points manually (if necessary),
		// that should be ok hopefully

		// We used to loop here and keep deleting anything we find,
		// but we are only allowed to remove symlinks, anything
		// else and MountMgr ignores the device.

**Comment by lundman** [comment]
OK so in the `zfs_lookup()` case (from a `CreateFile()`) we need to pay attention to `FILE_OPEN_REPARSE_POINT` - so that you can open the actual item, instead of always being forwarded.
Then I added a `DeleteReparsePoint()` which will open the reparse point (using `FILE_OPEN_REPARSE_POINT`) , and remove the flag `ZFS_REPARSE`, and delete `ZPL_SA_SYMLINK` data. Making the mountpoint reparse point back into a regular directory.
Since that calls the FS with `FSCTL_DELETE_REPARSE_POINT` we now handle that IRP, calling `delete_reparse_point()` which does the flag removal, SA delete.

Finally `ioc_unmount()` will then call to delete reparse point after unmount, which leaves a regular directory that can (will) be deleted.

This part works.

However, the directory can not be removed, (not empty), I believe due to `vp->use_count` being 1. I need to track this down.

**Comment by lundman** [comment]
OK part one 3e83da0

still has the "Is Busy" problem you already mentioned
